### ISSUE TITLE
Prepper_main_in and Prepper_veracity_in don't seem to match

### ISSUE THREAD

**Issue by Freeport2** [billdonner/pumper#2]
The veracity file seems incomplete to me which seems to me to have produced an incomplete blender output file.  If I use the "gamedata" file as the readyforios01 file, the app is produced correctly.  However, if I use the blender ouput file as the readyforios01 file, the app is not produced correctly.  I thought the blender output file was supposed to be a more complete "gamedata" file.  Do I not understand?  I put the prepper_input_data, prepper_veracity_in, and blender-output files in gd with a prefix of cf_

**Comment by billdonner** [comment]
Im going to split up pumper and prepare and make a new picture and have nothing with dual roles and the process will be totally sequential and easy to follow
